export const regions = [
  { label: "New York, NY", value: "New York, NY" },
  { label: "Los Angeles, CA", value: "Los Angeles, CA" },
  { label: "Chicago, IL", value: "Chicago, IL" },
  { label: "Dallas, TX", value: "Dallas, TX" },
  { label: "Houston, TX", value: "Houston, TX" },
  { label: "Washington, DC", value: "Washington, DC" },
  { label: "Philadelphia, PA", value: "Philadelphia, PA" },
  { label: "Miami, FL", value: "Miami, FL" },
  { label: "Atlanta, GA", value: "Atlanta, GA" },
  { label: "Boston, MA", value: "Boston, MA" },
  { label: "Phoenix, AZ", value: "Phoenix, AZ" },
  { label: "San Francisco, CA", value: "San Francisco, CA" },
  { label: "Riverside, CA", value: "Riverside, CA" },
  { label: "Detroit, MI", value: "Detroit, MI" },
  { label: "Seattle, WA", value: "Seattle, WA" },
  { label: "Minneapolis, MN", value: "Minneapolis, MN" },
  { label: "San Diego, CA", value: "San Diego, CA" },
  { label: "Tampa, FL", value: "Tampa, FL" },
  { label: "Denver, CO", value: "Denver, CO" },
  { label: "Baltimore, MD", value: "Baltimore, MD" },
  { label: "St. Louis, MO", value: "St. Louis, MO" },
  { label: "Orlando, FL", value: "Orlando, FL" },
  { label: "Charlotte, NC", value: "Charlotte, NC" },
  { label: "San Antonio, TX", value: "San Antonio, TX" },
  { label: "Portland, OR", value: "Portland, OR" },
  { label: "Sacramento, CA", value: "Sacramento, CA" },
  { label: "Pittsburgh, PA", value: "Pittsburgh, PA" },
  { label: "Cincinnati, OH", value: "Cincinnati, OH" },
  { label: "Austin, TX", value: "Austin, TX" },
  { label: "Las Vegas, NV", value: "Las Vegas, NV" },
  { label: "Kansas City, MO", value: "Kansas City, MO" },
  { label: "Columbus, OH", value: "Columbus, OH" },
  { label: "Indianapolis, IN", value: "Indianapolis, IN" },
  { label: "Cleveland, OH", value: "Cleveland, OH" },
  { label: "San Jose, CA", value: "San Jose, CA" },
  { label: "Nashville, TN", value: "Nashville, TN" },
  { label: "Virginia Beach, VA", value: "Virginia Beach, VA" },
  { label: "Providence, RI", value: "Providence, RI" },
  { label: "Jacksonville, FL", value: "Jacksonville, FL" },
  { label: "Milwaukee, WI", value: "Milwaukee, WI" },
  { label: "Oklahoma City, OK", value: "Oklahoma City, OK" },
  { label: "Raleigh, NC", value: "Raleigh, NC" },
  { label: "Memphis, TN", value: "Memphis, TN" },
  { label: "Richmond, VA", value: "Richmond, VA" },
  { label: "Louisville, KY", value: "Louisville, KY" },
  { label: "New Orleans, LA", value: "New Orleans, LA" },
  { label: "Salt Lake City, UT", value: "Salt Lake City, UT" },
  { label: "Hartford, CT", value: "Hartford, CT" },
  { label: "Buffalo, NY", value: "Buffalo, NY" },
  { label: "Birmingham, AL", value: "Birmingham, AL" },
  { label: "Rochester, NY", value: "Rochester, NY" },
  { label: "Grand Rapids, MI", value: "Grand Rapids, MI" },
  { label: "Tucson, AZ", value: "Tucson, AZ" },
  { label: "Urban Honolulu, HI", value: "Urban Honolulu, HI" },
  { label: "Tulsa, OK", value: "Tulsa, OK" },
  { label: "Fresno, CA", value: "Fresno, CA" },
  { label: "Worcester, MA", value: "Worcester, MA" },
  { label: "Omaha, NE", value: "Omaha, NE" },
  { label: "Bridgeport, CT", value: "Bridgeport, CT" },
  { label: "Greenville, SC", value: "Greenville, SC" },
  { label: "Albuquerque, NM", value: "Albuquerque, NM" },
  { label: "Bakersfield, CA", value: "Bakersfield, CA" },
  { label: "Albany, NY", value: "Albany, NY" },
  { label: "Knoxville, TN", value: "Knoxville, TN" },
  { label: "Baton Rouge, LA", value: "Baton Rouge, LA" },
  { label: "McAllen, TX", value: "McAllen, TX" },
  { label: "New Haven, CT", value: "New Haven, CT" },
  { label: "El Paso, TX", value: "El Paso, TX" },
  { label: "Allentown, PA", value: "Allentown, PA" },
  { label: "Oxnard, CA", value: "Oxnard, CA" },
  { label: "Columbia, SC", value: "Columbia, SC" },
  { label: "North Port, FL", value: "North Port, FL" },
  { label: "Charleston, SC", value: "Charleston, SC" },
  { label: "Greensboro, NC", value: "Greensboro, NC" },
  { label: "Stockton, CA", value: "Stockton, CA" },
  { label: "Cape Coral, FL", value: "Cape Coral, FL" },
  { label: "Boise City, ID", value: "Boise City, ID" },
  { label: "Colorado Springs, CO", value: "Colorado Springs, CO" },
  { label: "Little Rock, AR", value: "Little Rock, AR" },
  { label: "Lakeland, FL", value: "Lakeland, FL" },
  { label: "Akron, OH", value: "Akron, OH" },
  { label: "Des Moines, IA", value: "Des Moines, IA" },
  { label: "Springfield, MA", value: "Springfield, MA" },
  { label: "Ogden, UT", value: "Ogden, UT" },
  { label: "Madison, WI", value: "Madison, WI" },
  { label: "Winston, NC", value: "Winston, NC" },
  { label: "Deltona, FL", value: "Deltona, FL" },
  { label: "Syracuse, NY", value: "Syracuse, NY" },
  { label: "Provo, UT", value: "Provo, UT" },
  { label: "Toledo, OH", value: "Toledo, OH" },
  { label: "Wichita, KS", value: "Wichita, KS" },
  { label: "Durham, NC", value: "Durham, NC" },
  { label: "Augusta, GA", value: "Augusta, GA" },
  { label: "Palm Bay, FL", value: "Palm Bay, FL" },
  { label: "Jackson, MS", value: "Jackson, MS" },
  { label: "Harrisburg, PA", value: "Harrisburg, PA" },
  { label: "Spokane, WA", value: "Spokane, WA" },
  { label: "Scranton, PA", value: "Scranton, PA" },
  { label: "Chattanooga, TN", value: "Chattanooga, TN" },
  { label: "Modesto, CA", value: "Modesto, CA" },
  { label: "Lancaster, PA", value: "Lancaster, PA" },
  { label: "Portland, ME", value: "Portland, ME" },
  { label: "Youngstown, OH", value: "Youngstown, OH" },
  { label: "Lansing, MI", value: "Lansing, MI" },
  { label: "Fayetteville, AR", value: "Fayetteville, AR" },
  { label: "Fayetteville, NC", value: "Fayetteville, NC" },
  { label: "Lexington, KY", value: "Lexington, KY" },
  { label: "Pensacola, FL", value: "Pensacola, FL" },
  { label: "Santa Rosa, CA", value: "Santa Rosa, CA" },
  { label: "Reno, NV", value: "Reno, NV" },
  { label: "Huntsville, AL", value: "Huntsville, AL" },
  { label: "Port St. Lucie, FL", value: "Port St. Lucie, FL" },
  { label: "Lafayette, LA", value: "Lafayette, LA" },
  { label: "Myrtle Beach, SC", value: "Myrtle Beach, SC" },
  { label: "Springfield, MO", value: "Springfield, MO" },
  { label: "Visalia, CA", value: "Visalia, CA" },
  { label: "Killeen, TX", value: "Killeen, TX" },
  { label: "Asheville, NC", value: "Asheville, NC" },
  { label: "York, PA", value: "York, PA" },
  { label: "Vallejo, CA", value: "Vallejo, CA" },
  { label: "Santa Maria, CA", value: "Santa Maria, CA" },
  { label: "Salinas, CA", value: "Salinas, CA" },
  { label: "Salem, OR", value: "Salem, OR" },
  { label: "Mobile, AL", value: "Mobile, AL" },
  { label: "Reading, PA", value: "Reading, PA" },
  { label: "Corpus Christi, TX", value: "Corpus Christi, TX" },
  { label: "Brownsville, TX", value: "Brownsville, TX" },
  { label: "Manchester, NH", value: "Manchester, NH" },
  { label: "Fort Wayne, IN", value: "Fort Wayne, IN" },
  { label: "Gulfport, MS", value: "Gulfport, MS" },
  { label: "Salisbury, MD", value: "Salisbury, MD" },
  { label: "Flint, MI", value: "Flint, MI" },
  { label: "Peoria, IL", value: "Peoria, IL" },
  { label: "Canton, OH", value: "Canton, OH" },
  { label: "Savannah, GA", value: "Savannah, GA" },
  { label: "Anchorage, AK", value: "Anchorage, AK" },
  { label: "Beaumont, TX", value: "Beaumont, TX" },
  { label: "Shreveport, LA", value: "Shreveport, LA" },
  { label: "Trenton, NJ", value: "Trenton, NJ" },
  { label: "Montgomery, AL", value: "Montgomery, AL" },
  { label: "Davenport, IA", value: "Davenport, IA" },
  { label: "Tallahassee, FL", value: "Tallahassee, FL" },
  { label: "Eugene, OR", value: "Eugene, OR" },
  { label: "Naples, FL", value: "Naples, FL" },
  { label: "Ann Arbor, MI", value: "Ann Arbor, MI" },
  { label: "Ocala, FL", value: "Ocala, FL" },
  { label: "Hickory, NC", value: "Hickory, NC" },
  { label: "Huntington, WV", value: "Huntington, WV" },
  { label: "Fort Collins, CO", value: "Fort Collins, CO" },
  { label: "Rockford, IL", value: "Rockford, IL" },
  { label: "Lincoln, NE", value: "Lincoln, NE" },
  { label: "Gainesville, FL", value: "Gainesville, FL" },
  { label: "Boulder, CO", value: "Boulder, CO" },
  { label: "Green Bay, WI", value: "Green Bay, WI" },
  { label: "Columbus, GA", value: "Columbus, GA" },
  { label: "South Bend, IN", value: "South Bend, IN" },
  { label: "Spartanburg, SC", value: "Spartanburg, SC" },
  { label: "Greeley, CO", value: "Greeley, CO" },
  { label: "Lubbock, TX", value: "Lubbock, TX" },
  { label: "Clarksville, TN", value: "Clarksville, TN" },
  { label: "Roanoke, VA", value: "Roanoke, VA" },
  { label: "Evansville, IN", value: "Evansville, IN" },
  { label: "Kingsport, TN", value: "Kingsport, TN" },
  { label: "Kennewick, WA", value: "Kennewick, WA" },
  { label: "Utica, NY", value: "Utica, NY" },
  { label: "Hagerstown, MD", value: "Hagerstown, MD" },
  { label: "Duluth, MN", value: "Duluth, MN" },
  { label: "Olympia, WA", value: "Olympia, WA" },
  { label: "Longview, TX", value: "Longview, TX" },
  { label: "Wilmington, NC", value: "Wilmington, NC" },
  { label: "San Luis Obispo, CA", value: "San Luis Obispo, CA" },
  { label: "Crestview, FL", value: "Crestview, FL" },
  { label: "Merced, CA", value: "Merced, CA" },
  { label: "Waco, TX", value: "Waco, TX" },
  { label: "Cedar Rapids, IA", value: "Cedar Rapids, IA" },
  { label: "Atlantic City, NJ", value: "Atlantic City, NJ" },
  { label: "Bremerton, WA", value: "Bremerton, WA" },
  { label: "Sioux Falls, SD", value: "Sioux Falls, SD" },
  { label: "Santa Cruz, CA", value: "Santa Cruz, CA" },
  { label: "Erie, PA", value: "Erie, PA" },
  { label: "Norwich, CT", value: "Norwich, CT" },
  { label: "Amarillo, TX", value: "Amarillo, TX" },
  { label: "Laredo, TX", value: "Laredo, TX" },
  { label: "Tuscaloosa, AL", value: "Tuscaloosa, AL" },
  { label: "College Station, TX", value: "College Station, TX" },
  { label: "Kalamazoo, MI", value: "Kalamazoo, MI" },
  { label: "Lynchburg, VA", value: "Lynchburg, VA" },
  { label: "Charleston, WV", value: "Charleston, WV" },
  { label: "Yakima, WA", value: "Yakima, WA" },
  { label: "Fargo, ND", value: "Fargo, ND" },
  { label: "Binghamton, NY", value: "Binghamton, NY" },
  { label: "Fort Smith, AR", value: "Fort Smith, AR" },
  { label: "Appleton, WI", value: "Appleton, WI" },
  { label: "Topeka, KS", value: "Topeka, KS" },
  { label: "Macon, GA", value: "Macon, GA" },
  { label: "Tyler, TX", value: "Tyler, TX" },
  { label: "Barnstable Town, MA", value: "Barnstable Town, MA" },
  { label: "Daphne, AL", value: "Daphne, AL" },
  { label: "Bellingham, WA", value: "Bellingham, WA" },
  { label: "Burlington, VT", value: "Burlington, VT" },
  { label: "Rochester, MN", value: "Rochester, MN" },
  { label: "Lafayette, IN", value: "Lafayette, IN" },
  { label: "Champaign, IL", value: "Champaign, IL" },
  { label: "Medford, OR", value: "Medford, OR" },
  { label: "Charlottesville, VA", value: "Charlottesville, VA" },
  { label: "Lake Charles, LA", value: "Lake Charles, LA" },
  { label: "Las Cruces, NM", value: "Las Cruces, NM" },
  { label: "Chico, CA", value: "Chico, CA" },
  { label: "Hilton Head Island, SC", value: "Hilton Head Island, SC" },
  { label: "Athens, GA", value: "Athens, GA" },
  { label: "Lake Havasu City, AZ", value: "Lake Havasu City, AZ" },
  { label: "Columbia, MO", value: "Columbia, MO" },
  { label: "Springfield, IL", value: "Springfield, IL" },
  { label: "Houma, LA", value: "Houma, LA" },
  { label: "Monroe, LA", value: "Monroe, LA" },
  { label: "Elkhart, IN", value: "Elkhart, IN" },
  { label: "Johnson City, TN", value: "Johnson City, TN" },
  { label: "Yuma, AZ", value: "Yuma, AZ" },
  { label: "Gainesville, GA", value: "Gainesville, GA" },
  { label: "Jacksonville, NC", value: "Jacksonville, NC" },
  { label: "Florence, SC", value: "Florence, SC" },
  { label: "Hilo, HI", value: "Hilo, HI" },
  { label: "St. Cloud, MN", value: "St. Cloud, MN" },
  { label: "Racine, WI", value: "Racine, WI" },
  { label: "Bend, OR", value: "Bend, OR" },
  { label: "Saginaw, MI", value: "Saginaw, MI" },
  { label: "Warner Robins, GA", value: "Warner Robins, GA" },
  { label: "Terre Haute, IN", value: "Terre Haute, IN" },
  { label: "Torrington, CT", value: "Torrington, CT" },
  { label: "Punta Gorda, FL", value: "Punta Gorda, FL" },
  { label: "Billings, MT", value: "Billings, MT" },
  { label: "Redding, CA", value: "Redding, CA" },
  { label: "Kingston, NY", value: "Kingston, NY" },
  { label: "Panama City, FL", value: "Panama City, FL" },
  { label: "Joplin, MO", value: "Joplin, MO" },
  { label: "Dover, DE", value: "Dover, DE" },
  { label: "El Centro, CA", value: "El Centro, CA" },
  { label: "Jackson, TN", value: "Jackson, TN" },
  { label: "Yuba City, CA", value: "Yuba City, CA" },
  { label: "Bowling Green, KY", value: "Bowling Green, KY" },
  { label: "St. George, UT", value: "St. George, UT" },
  { label: "Muskegon, MI", value: "Muskegon, MI" },
  { label: "Abilene, TX", value: "Abilene, TX" },
  { label: "Iowa City, IA", value: "Iowa City, IA" },
  { label: "Auburn, AL", value: "Auburn, AL" },
  { label: "Midland, TX", value: "Midland, TX" },
  { label: "Bloomington, IL", value: "Bloomington, IL" },
  { label: "Hattiesburg, MS", value: "Hattiesburg, MS" },
  { label: "Oshkosh, WI", value: "Oshkosh, WI" },
  { label: "Eau Claire, WI", value: "Eau Claire, WI" },
  { label: "Greenville, NC", value: "Greenville, NC" },
  { label: "Burlington, NC", value: "Burlington, NC" },
  { label: "Waterloo, IA", value: "Waterloo, IA" },
  { label: "Coeur d'Alene, ID", value: "Coeur d'Alene, ID" },
  { label: "East Stroudsburg, PA", value: "East Stroudsburg, PA" },
  { label: "Pueblo, CO", value: "Pueblo, CO" },
  { label: "Blacksburg, VA", value: "Blacksburg, VA" },
  { label: "Wausau, WI", value: "Wausau, WI" },
  { label: "Kahului, HI", value: "Kahului, HI" },
  { label: "Janesville, WI", value: "Janesville, WI" },
  { label: "Tupelo, MS", value: "Tupelo, MS" },
  { label: "Bloomington, IN", value: "Bloomington, IN" },
  { label: "Odessa, TX", value: "Odessa, TX" },
  { label: "Jackson, MI", value: "Jackson, MI" },
  { label: "State College, PA", value: "State College, PA" },
  { label: "Sebastian, FL", value: "Sebastian, FL" },
  { label: "Madera, CA", value: "Madera, CA" },
  { label: "Decatur, AL", value: "Decatur, AL" },
  { label: "Chambersburg, PA", value: "Chambersburg, PA" },
  { label: "Vineland, NJ", value: "Vineland, NJ" },
  { label: "Idaho Falls, ID", value: "Idaho Falls, ID" },
  { label: "Grand Junction, CO", value: "Grand Junction, CO" },
  { label: "Elizabethtown, KY", value: "Elizabethtown, KY" },
  { label: "Niles, MI", value: "Niles, MI" },
  { label: "Monroe, MI", value: "Monroe, MI" },
  { label: "Santa Fe, NM", value: "Santa Fe, NM" },
  { label: "Concord, NH", value: "Concord, NH" },
  { label: "Alexandria, LA", value: "Alexandria, LA" },
  { label: "Traverse City, MI", value: "Traverse City, MI" },
  { label: "Bangor, ME", value: "Bangor, ME" },
  { label: "Homosassa Springs, FL", value: "Homosassa Springs, FL" },
  { label: "Hanford, CA", value: "Hanford, CA" },
  { label: "Jefferson City, MO", value: "Jefferson City, MO" },
  { label: "Florence, AL", value: "Florence, AL" },
  { label: "Dothan, AL", value: "Dothan, AL" },
  { label: "London, KY", value: "London, KY" },
  { label: "Albany, GA", value: "Albany, GA" },
  { label: "Sioux City, IA", value: "Sioux City, IA" },
  { label: "Wichita Falls, TX", value: "Wichita Falls, TX" },
  { label: "Texarkana, TX", value: "Texarkana, TX" },
  { label: "Valdosta, GA", value: "Valdosta, GA" },
  { label: "Logan, UT", value: "Logan, UT" },
  { label: "Flagstaff, AZ", value: "Flagstaff, AZ" },
  { label: "Rocky Mount, NC", value: "Rocky Mount, NC" },
  { label: "Pottsville, PA", value: "Pottsville, PA" },
  { label: "Dalton, GA", value: "Dalton, GA" },
  { label: "Lebanon, PA", value: "Lebanon, PA" },
  { label: "Morristown, TN", value: "Morristown, TN" },
  { label: "Winchester, VA", value: "Winchester, VA" },
  { label: "Wheeling, WV", value: "Wheeling, WV" },
  { label: "Morgantown, WV", value: "Morgantown, WV" },
  { label: "La Crosse, WI", value: "La Crosse, WI" },
  { label: "Napa, CA", value: "Napa, CA" },
  { label: "Rapid City, SD", value: "Rapid City, SD" },
  { label: "Sumter, SC", value: "Sumter, SC" },
  { label: "Eureka, CA", value: "Eureka, CA" },
  { label: "Springfield, OH", value: "Springfield, OH" },
  { label: "Harrisonburg, VA", value: "Harrisonburg, VA" },
  { label: "Battle Creek, MI", value: "Battle Creek, MI" },
  { label: "Sherman, TX", value: "Sherman, TX" },
  { label: "Manhattan, KS", value: "Manhattan, KS" },
  { label: "Carbondale, IL", value: "Carbondale, IL" },
  { label: "Johnstown, PA", value: "Johnstown, PA" },
  { label: "Jonesboro, AR", value: "Jonesboro, AR" },
  { label: "Bismarck, ND", value: "Bismarck, ND" },
  { label: "Hammond, LA", value: "Hammond, LA" },
  { label: "Pittsfield, MA", value: "Pittsfield, MA" },
  { label: "Mount Vernon, WA", value: "Mount Vernon, WA" },
  { label: "Jamestown, NY", value: "Jamestown, NY" },
  { label: "The Villages, FL", value: "The Villages, FL" },
  { label: "Albany, OR", value: "Albany, OR" },
  { label: "Glens Falls, NY", value: "Glens Falls, NY" },
  { label: "Lawton, OK", value: "Lawton, OK" },
  { label: "Cleveland, TN", value: "Cleveland, TN" },
  { label: "Sierra Vista, AZ", value: "Sierra Vista, AZ" },
  { label: "Ames, IA", value: "Ames, IA" },
  { label: "Mansfield, OH", value: "Mansfield, OH" },
  { label: "Staunton, VA", value: "Staunton, VA" },
  { label: "Augusta, ME", value: "Augusta, ME" },
  { label: "Altoona, PA", value: "Altoona, PA" },
  { label: "New Bern, NC", value: "New Bern, NC" },
  { label: "Farmington, NM", value: "Farmington, NM" },
  { label: "St. Joseph, MO", value: "St. Joseph, MO" },
  { label: "San Angelo, TX", value: "San Angelo, TX" },
  { label: "Wenatchee, WA", value: "Wenatchee, WA" },
  { label: "Owensboro, KY", value: "Owensboro, KY" },
  { label: "Holland, MI", value: "Holland, MI" },
  { label: "Lumberton, NC", value: "Lumberton, NC" },
  { label: "Lawrence, KS", value: "Lawrence, KS" },
  { label: "Goldsboro, NC", value: "Goldsboro, NC" },
  { label: "Watertown, NY", value: "Watertown, NY" },
  { label: "Sheboygan, WI", value: "Sheboygan, WI" },
  { label: "Weirton, WV", value: "Weirton, WV" },
  { label: "Missoula, MT", value: "Missoula, MT" },
  { label: "Bozeman, MT", value: "Bozeman, MT" },
  { label: "Anniston, AL", value: "Anniston, AL" },
  { label: "Beckley, WV", value: "Beckley, WV" },
  { label: "Williamsport, PA", value: "Williamsport, PA" },
  { label: "Brunswick, GA", value: "Brunswick, GA" },
  { label: "California, MD", value: "California, MD" },
  { label: "Twin Falls, ID", value: "Twin Falls, ID" },
  { label: "Cookeville, TN", value: "Cookeville, TN" },
  { label: "Muncie, IN", value: "Muncie, IN" },
  { label: "Michigan City, IN", value: "Michigan City, IN" },
  { label: "Roseburg, OR", value: "Roseburg, OR" },
  { label: "Lewiston, ME", value: "Lewiston, ME" },
  { label: "Longview, WA", value: "Longview, WA" },
  { label: "Ogdensburg, NY", value: "Ogdensburg, NY" },
  { label: "Kankakee, IL", value: "Kankakee, IL" },
  { label: "Bluefield, WV", value: "Bluefield, WV" },
  { label: "Show Low, AZ", value: "Show Low, AZ" },
  { label: "Richmond, KY", value: "Richmond, KY" },
  { label: "Tullahoma, TN", value: "Tullahoma, TN" },
  { label: "Whitewater, WI", value: "Whitewater, WI" },
  { label: "Ithaca, NY", value: "Ithaca, NY" },
  { label: "Grand Forks, ND", value: "Grand Forks, ND" },
  { label: "Decatur, IL", value: "Decatur, IL" },
  { label: "LaGrange, GA", value: "LaGrange, GA" },
  { label: "Bay City, MI", value: "Bay City, MI" },
  { label: "Fond du Lac, WI", value: "Fond du Lac, WI" },
  { label: "Gettysburg, PA", value: "Gettysburg, PA" },
  { label: "Gadsden, AL", value: "Gadsden, AL" },
  { label: "Kalispell, MT", value: "Kalispell, MT" },
  { label: "Danville, VA", value: "Danville, VA" },
  { label: "Mankato, MN", value: "Mankato, MN" },
  { label: "Lima, OH", value: "Lima, OH" },
  { label: "Salem, OH", value: "Salem, OH" },
  { label: "Truckee, CA", value: "Truckee, CA" },
  { label: "Sebring, FL", value: "Sebring, FL" },
  { label: "Cheyenne, WY", value: "Cheyenne, WY" },
  { label: "Hot Springs, AR", value: "Hot Springs, AR" },
  { label: "Adrian, MI", value: "Adrian, MI" },
  { label: "Shelby, NC", value: "Shelby, NC" },
  { label: "Dubuque, IA", value: "Dubuque, IA" },
  { label: "Meridian, MS", value: "Meridian, MS" },
  { label: "Pinehurst, NC", value: "Pinehurst, NC" },
  { label: "Paducah, KY", value: "Paducah, KY" },
  { label: "Victoria, TX", value: "Victoria, TX" },
  { label: "Rome, GA", value: "Rome, GA" },
  { label: "Sevierville, TN", value: "Sevierville, TN" },
  { label: "Moses Lake, WA", value: "Moses Lake, WA" },
  { label: "Ashtabula, OH", value: "Ashtabula, OH" },
  { label: "Cape Girardeau, MO", value: "Cape Girardeau, MO" },
  { label: "Albertville, AL", value: "Albertville, AL" },
  { label: "Fairbanks, AK", value: "Fairbanks, AK" },
  { label: "Brainerd, MN", value: "Brainerd, MN" },
  { label: "Cumberland, MD", value: "Cumberland, MD" },
  { label: "Ocean City, NJ", value: "Ocean City, NJ" },
  { label: "Corvallis, OR", value: "Corvallis, OR" },
  { label: "Pocatello, ID", value: "Pocatello, ID" },
  { label: "Corning, NY", value: "Corning, NY" },
  { label: "New Philadelphia, OH", value: "New Philadelphia, OH" },
  { label: "Sunbury, PA", value: "Sunbury, PA" },
  { label: "Ukiah, CA", value: "Ukiah, CA" },
  { label: "Hermiston, OR", value: "Hermiston, OR" },
  { label: "Clarksburg, WV", value: "Clarksburg, WV" },
  { label: "Parkersburg, WV", value: "Parkersburg, WV" },
  { label: "Beaver Dam, WI", value: "Beaver Dam, WI" },
  { label: "Pine Bluff, AR", value: "Pine Bluff, AR" },
  { label: "Grants Pass, OR", value: "Grants Pass, OR" },
  { label: "Cullman, AL", value: "Cullman, AL" },
  { label: "Lufkin, TX", value: "Lufkin, TX" },
  { label: "Zanesville, OH", value: "Zanesville, OH" },
  { label: "New Castle, PA", value: "New Castle, PA" },
  { label: "Oak Harbor, WA", value: "Oak Harbor, WA" },
  { label: "Orangeburg, SC", value: "Orangeburg, SC" },
  { label: "Watertown, WI", value: "Watertown, WI" },
  { label: "Meadville, PA", value: "Meadville, PA" },
  { label: "Elmira, NY", value: "Elmira, NY" },
  { label: "Great Falls, MT", value: "Great Falls, MT" },
  { label: "Laurel, MS", value: "Laurel, MS" },
  { label: "Russellville, AR", value: "Russellville, AR" },
  { label: "Indiana, PA", value: "Indiana, PA" },
  { label: "Midland, MI", value: "Midland, MI" },
  { label: "Kokomo, IN", value: "Kokomo, IN" },
  { label: "Bloomsburg, PA", value: "Bloomsburg, PA" },
  { label: "Opelousas, LA", value: "Opelousas, LA" },
  { label: "Helena, MT", value: "Helena, MT" },
  { label: "Key West, FL", value: "Key West, FL" },
  { label: "Talladega, AL", value: "Talladega, AL" },
  { label: "Stillwater, OK", value: "Stillwater, OK" },
  { label: "Columbus, IN", value: "Columbus, IN" },
  { label: "Athens, TX", value: "Athens, TX" },
  { label: "Centralia, WA", value: "Centralia, WA" },
  { label: "Manitowoc, WI", value: "Manitowoc, WI" },
  { label: "Hinesville, GA", value: "Hinesville, GA" },
  { label: "DuBois, PA", value: "DuBois, PA" },
  { label: "Warsaw, IN", value: "Warsaw, IN" },
  { label: "Plattsburgh, NY", value: "Plattsburgh, NY" },
  { label: "Statesboro, GA", value: "Statesboro, GA" },
  { label: "Casper, WY", value: "Casper, WY" },
  { label: "Wilson, NC", value: "Wilson, NC" },
  { label: "Glenwood Springs, CO", value: "Glenwood Springs, CO" },
  { label: "Seneca, SC", value: "Seneca, SC" },
  { label: "Minot, ND", value: "Minot, ND" },
  { label: "Olean, NY", value: "Olean, NY" },
  { label: "Chillicothe, OH", value: "Chillicothe, OH" },
  { label: "Searcy, AR", value: "Searcy, AR" },
  { label: "Grand Island, NE", value: "Grand Island, NE" },
  { label: "Port Angeles, WA", value: "Port Angeles, WA" },
  { label: "Auburn, NY", value: "Auburn, NY" },
  { label: "Huntsville, TX", value: "Huntsville, TX" },
  { label: "Keene, NH", value: "Keene, NH" },
  { label: "Heber, UT", value: "Heber, UT" },
  { label: "Quincy, IL", value: "Quincy, IL" },
  { label: "Sandusky, OH", value: "Sandusky, OH" },
  { label: "Findlay, OH", value: "Findlay, OH" },
  { label: "Frankfort, KY", value: "Frankfort, KY" },
  { label: "Danville, IL", value: "Danville, IL" },
  { label: "Aberdeen, WA", value: "Aberdeen, WA" },
  { label: "Portsmouth, OH", value: "Portsmouth, OH" },
  { label: "Somerset, PA", value: "Somerset, PA" },
  { label: "Wisconsin Rapids, WI", value: "Wisconsin Rapids, WI" },
  { label: "Jefferson, GA", value: "Jefferson, GA" },
  { label: "Kapaa, HI", value: "Kapaa, HI" },
  { label: "Palatka, FL", value: "Palatka, FL" },
  { label: "Gallup, NM", value: "Gallup, NM" },
  { label: "Hobbs, NM", value: "Hobbs, NM" },
  { label: "Shawnee, OK", value: "Shawnee, OK" },
  { label: "Mount Airy, NC", value: "Mount Airy, NC" },
  { label: "Stevens Point, WI", value: "Stevens Point, WI" },
  { label: "Greeneville, TN", value: "Greeneville, TN" },
  { label: "Greenwood, SC", value: "Greenwood, SC" },
  { label: "Lake City, FL", value: "Lake City, FL" },
  { label: "Klamath Falls, OR", value: "Klamath Falls, OR" },
  { label: "Morehead City, NC", value: "Morehead City, NC" },
  { label: "Clearlake, CA", value: "Clearlake, CA" },
  { label: "Alamogordo, NM", value: "Alamogordo, NM" },
  { label: "Roanoke Rapids, NC", value: "Roanoke Rapids, NC" },
  { label: "Farmington, MO", value: "Farmington, MO" },
  { label: "Muskogee, OK", value: "Muskogee, OK" },
  { label: "Marion, IN", value: "Marion, IN" },
  { label: "Faribault, MN", value: "Faribault, MN" },
  { label: "Richmond, IN", value: "Richmond, IN" },
  { label: "Marquette, MI", value: "Marquette, MI" },
  { label: "North Wilkesboro, NC", value: "North Wilkesboro, NC" },
  { label: "Mount Pleasant, MI", value: "Mount Pleasant, MI" },
  { label: "Rio Grande City, TX", value: "Rio Grande City, TX" },
  { label: "Marion, OH", value: "Marion, OH" },
  { label: "Baraboo, WI", value: "Baraboo, WI" },
  { label: "Red Bluff, CA", value: "Red Bluff, CA" },
  { label: "Marinette, WI", value: "Marinette, WI" },
  { label: "Roswell, NM", value: "Roswell, NM" },
  { label: "Shelton, WA", value: "Shelton, WA" },
  { label: "Dublin, GA", value: "Dublin, GA" },
  { label: "Nacogdoches, TX", value: "Nacogdoches, TX" },
  { label: "Somerset, KY", value: "Somerset, KY" },
  { label: "Coos Bay, OR", value: "Coos Bay, OR" },
  { label: "Forest City, NC", value: "Forest City, NC" },
  { label: "Martinsville, VA", value: "Martinsville, VA" },
  { label: "Rexburg, ID", value: "Rexburg, ID" },
  { label: "Lewiston, ID", value: "Lewiston, ID" },
  { label: "Laconia, NH", value: "Laconia, NH" },
  { label: "Georgetown, SC", value: "Georgetown, SC" },
  { label: "Athens, OH", value: "Athens, OH" },
  { label: "Sanford, NC", value: "Sanford, NC" },
  { label: "Enid, OK", value: "Enid, OK" },
  { label: "Mount Vernon, OH", value: "Mount Vernon, OH" },
  { label: "Walla Walla, WA", value: "Walla Walla, WA" },
  { label: "Albemarle, NC", value: "Albemarle, NC" },
  { label: "Hutchinson, KS", value: "Hutchinson, KS" },
  { label: "Hudson, NY", value: "Hudson, NY" },
  { label: "Starkville, MS", value: "Starkville, MS" },
  { label: "Carlsbad, NM", value: "Carlsbad, NM" },
  { label: "Gillette, WY", value: "Gillette, WY" },
  { label: "Sturgis, MI", value: "Sturgis, MI" },
  { label: "Rutland, VT", value: "Rutland, VT" },
  { label: "Crossville, TN", value: "Crossville, TN" },
  { label: "Sayre, PA", value: "Sayre, PA" },
  { label: "Salina, KS", value: "Salina, KS" },
  { label: "Marietta, OH", value: "Marietta, OH" },
  { label: "Fergus Falls, MN", value: "Fergus Falls, MN" },
  { label: "Barre, VT", value: "Barre, VT" },
  { label: "Fremont, OH", value: "Fremont, OH" },
  { label: "Oneonta, NY", value: "Oneonta, NY" },
  { label: "Columbus, MS", value: "Columbus, MS" },
  { label: "Norwalk, OH", value: "Norwalk, OH" },
  { label: "Batavia, NY", value: "Batavia, NY" },
  { label: "Ardmore, OK", value: "Ardmore, OK" },
  { label: "Palestine, TX", value: "Palestine, TX" },
  { label: "Fort Madison, IA", value: "Fort Madison, IA" },
  { label: "Charleston, IL", value: "Charleston, IL" },
  { label: "Fernley, NV", value: "Fernley, NV" },
  { label: "Carson City, NV", value: "Carson City, NV" },
  { label: "Eagle Pass, TX", value: "Eagle Pass, TX" },
  { label: "Calhoun, GA", value: "Calhoun, GA" },
  { label: "Cullowhee, NC", value: "Cullowhee, NC" },
  { label: "Kearney, NE", value: "Kearney, NE" },
  { label: "Fairmont, WV", value: "Fairmont, WV" },
  { label: "Ontario, OR", value: "Ontario, OR" },
  { label: "Gaffney, SC", value: "Gaffney, SC" },
  { label: "Picayune, MS", value: "Picayune, MS" },
  { label: "Sterling, IL", value: "Sterling, IL" },
  { label: "Branson, MO", value: "Branson, MO" },
  { label: "Cedar City, UT", value: "Cedar City, UT" },
  { label: "Waycross, GA", value: "Waycross, GA" },
  { label: "Oxford, MS", value: "Oxford, MS" },
  { label: "Jasper, IN", value: "Jasper, IN" },
  { label: "Edwards, CO", value: "Edwards, CO" },
  { label: "Durango, CO", value: "Durango, CO" },
  { label: "Kinston, NC", value: "Kinston, NC" },
  { label: "Sonora, CA", value: "Sonora, CA" },
  { label: "Tiffin, OH", value: "Tiffin, OH" },
  { label: "Batesville, AR", value: "Batesville, AR" },
  { label: "Point Pleasant, WV", value: "Point Pleasant, WV" },
  { label: "Elko, NV", value: "Elko, NV" },
  { label: "Danville, KY", value: "Danville, KY" },
  { label: "Glasgow, KY", value: "Glasgow, KY" },
  { label: "St. Marys, GA", value: "St. Marys, GA" },
  { label: "Boone, NC", value: "Boone, NC" },
  { label: "Warrensburg, MO", value: "Warrensburg, MO" },
  { label: "Gloversville, NY", value: "Gloversville, NY" },
  { label: "Fort Leonard Wood, MO", value: "Fort Leonard Wood, MO" },
  { label: "Poplar Bluff, MO", value: "Poplar Bluff, MO" },
  { label: "Elizabeth City, NC", value: "Elizabeth City, NC" },
  { label: "Payson, AZ", value: "Payson, AZ" },
  { label: "Athens, TN", value: "Athens, TN" },
  { label: "Enterprise, AL", value: "Enterprise, AL" },
  { label: "Ashland, OH", value: "Ashland, OH" },
  { label: "Scottsboro, AL", value: "Scottsboro, AL" },
  { label: "Milledgeville, GA", value: "Milledgeville, GA" },
  { label: "Kerrville, TX", value: "Kerrville, TX" },
  { label: "Bartlesville, OK", value: "Bartlesville, OK" },
  { label: "Platteville, WI", value: "Platteville, WI" },
  { label: "Corsicana, TX", value: "Corsicana, TX" },
  { label: "Greenville, OH", value: "Greenville, OH" },
  { label: "Rochelle, IL", value: "Rochelle, IL" },
  { label: "Douglas, GA", value: "Douglas, GA" },
  { label: "Oil City, PA", value: "Oil City, PA" },
  { label: "Mason City, IA", value: "Mason City, IA" },
  { label: "Jacksonville, TX", value: "Jacksonville, TX" },
  { label: "Galesburg, IL", value: "Galesburg, IL" },
  { label: "Pahrump, NV", value: "Pahrump, NV" },
  { label: "Paris, TX", value: "Paris, TX" },
  { label: "Winona, MN", value: "Winona, MN" },
  { label: "Newport, OR", value: "Newport, OR" },
  { label: "Morgan City, LA", value: "Morgan City, LA" },
  { label: "Shelbyville, TN", value: "Shelbyville, TN" },
  { label: "Amsterdam, NY", value: "Amsterdam, NY" },
  { label: "Ozark, AL", value: "Ozark, AL" },
  { label: "Alice, TX", value: "Alice, TX" },
  { label: "Gardnerville Ranchos, NV", value: "Gardnerville Ranchos, NV" },
  { label: "Fort Polk South, LA", value: "Fort Polk South, LA" },
  { label: "Ca-¦on City, CO", value: "Ca-¦on City, CO" },
  { label: "Natchez, MS", value: "Natchez, MS" },
  { label: "New Castle, IN", value: "New Castle, IN" },
  { label: "Clovis, NM", value: "Clovis, NM" },
  { label: "Norfolk, NE", value: "Norfolk, NE" },
  { label: "Cadillac, MI", value: "Cadillac, MI" },
  { label: "Ruston, LA", value: "Ruston, LA" },
  { label: "Sidney, OH", value: "Sidney, OH" },
  { label: "Pullman, WA", value: "Pullman, WA" },
  { label: "Malone, NY", value: "Malone, NY" },
  { label: "Del Rio, TX", value: "Del Rio, TX" },
  { label: "Blackfoot, ID", value: "Blackfoot, ID" },
  { label: "Red Wing, MN", value: "Red Wing, MN" },
  { label: "Nogales, AZ", value: "Nogales, AZ" },
  { label: "Tahlequah, OK", value: "Tahlequah, OK" },
  { label: "Kendallville, IN", value: "Kendallville, IN" },
  { label: "Montrose, CO", value: "Montrose, CO" },
  { label: "Cortland, NY", value: "Cortland, NY" },
  { label: "Mount Sterling, KY", value: "Mount Sterling, KY" },
  { label: "Clinton, IA", value: "Clinton, IA" },
  { label: "Sandpoint, ID", value: "Sandpoint, ID" },
  { label: "Bardstown, KY", value: "Bardstown, KY" },
  { label: "Wapakoneta, OH", value: "Wapakoneta, OH" },
  { label: "Plymouth, IN", value: "Plymouth, IN" },
  { label: "Lewistown, PA", value: "Lewistown, PA" },
  { label: "Bemidji, MN", value: "Bemidji, MN" },
  { label: "Bellefontaine, OH", value: "Bellefontaine, OH" },
  { label: "Seymour, IN", value: "Seymour, IN" },
  { label: "Burley, ID", value: "Burley, ID" },
  { label: "Durant, OK", value: "Durant, OK" },
  { label: "Moultrie, GA", value: "Moultrie, GA" },
  { label: "Bogalusa, LA", value: "Bogalusa, LA" },
  { label: "Cornelia, GA", value: "Cornelia, GA" },
  { label: "Hillsdale, MI", value: "Hillsdale, MI" },
  { label: "Thomasville, GA", value: "Thomasville, GA" },
  { label: "Paragould, AR", value: "Paragould, AR" },
  { label: "Greenville, MS", value: "Greenville, MS" },
  { label: "Burlington, IA", value: "Burlington, IA" },
  { label: "Madisonville, KY", value: "Madisonville, KY" },
  { label: "Menomonie, WI", value: "Menomonie, WI" },
  { label: "Shawano, WI", value: "Shawano, WI" },
  { label: "Vicksburg, MS", value: "Vicksburg, MS" },
  { label: "Bedford, IN", value: "Bedford, IN" },
  { label: "Washington, NC", value: "Washington, NC" },
  { label: "Freeport, IL", value: "Freeport, IL" },
  { label: "Harrison, AR", value: "Harrison, AR" },
  { label: "Rolla, MO", value: "Rolla, MO" },
  { label: "Coldwater, MI", value: "Coldwater, MI" },
  { label: "Marion, NC", value: "Marion, NC" },
  { label: "Huntingdon, PA", value: "Huntingdon, PA" },
  { label: "Ellensburg, WA", value: "Ellensburg, WA" },
  { label: "Ponca City, OK", value: "Ponca City, OK" },
  { label: "Lawrenceburg, TN", value: "Lawrenceburg, TN" },
  { label: "McAlester, OK", value: "McAlester, OK" },
  { label: "Mount Pleasant, TX", value: "Mount Pleasant, TX" },
  { label: "Willmar, MN", value: "Willmar, MN" },
  { label: "Rockingham, NC", value: "Rockingham, NC" },
  { label: "Muscatine, IA", value: "Muscatine, IA" },
  { label: "Lewisburg, PA", value: "Lewisburg, PA" },
  { label: "Auburn, IN", value: "Auburn, IN" },
  { label: "Duncan, OK", value: "Duncan, OK" },
  { label: "Sedalia, MO", value: "Sedalia, MO" },
  { label: "Cedartown, GA", value: "Cedartown, GA" },
  { label: "Henderson, NC", value: "Henderson, NC" },
  { label: "Aberdeen, SD", value: "Aberdeen, SD" },
  { label: "Rock Springs, WY", value: "Rock Springs, WY" },
  { label: "Garden City, KS", value: "Garden City, KS" },
  { label: "Stephenville, TX", value: "Stephenville, TX" },
  { label: "Celina, OH", value: "Celina, OH" },
  { label: "Wilmington, OH", value: "Wilmington, OH" },
  { label: "Bucyrus, OH", value: "Bucyrus, OH" },
  { label: "Alma, MI", value: "Alma, MI" },
  { label: "El Campo, TX", value: "El Campo, TX" },
  { label: "Mountain Home, AR", value: "Mountain Home, AR" },
  { label: "Gainesville, TX", value: "Gainesville, TX" },
  { label: "Tifton, GA", value: "Tifton, GA" },
  { label: "Blytheville, AR", value: "Blytheville, AR" },
  { label: "McMinnville, TN", value: "McMinnville, TN" },
  { label: "Astoria, OR", value: "Astoria, OR" },
  { label: "Bradford, PA", value: "Bradford, PA" },
  { label: "Espa-¦ola, NM", value: "Espa-¦ola, NM" },
  { label: "McComb, MS", value: "McComb, MS" },
  { label: "Big Stone Gap, VA", value: "Big Stone Gap, VA" },
  { label: "Marshalltown, IA", value: "Marshalltown, IA" },
  { label: "Big Rapids, MI", value: "Big Rapids, MI" },
  { label: "Austin, MN", value: "Austin, MN" },
  { label: "Selinsgrove, PA", value: "Selinsgrove, PA" },
  { label: "West Plains, MO", value: "West Plains, MO" },
  { label: "Okeechobee, FL", value: "Okeechobee, FL" },
  { label: "Houghton, MI", value: "Houghton, MI" },
  { label: "Moscow, ID", value: "Moscow, ID" },
  { label: "Clewiston, FL", value: "Clewiston, FL" },
  { label: "Riverton, WY", value: "Riverton, WY" },
  { label: "El Dorado, AR", value: "El Dorado, AR" },
  { label: "Selma, AL", value: "Selma, AL" },
  { label: "Pittsburg, KS", value: "Pittsburg, KS" },
  { label: "Hannibal, MO", value: "Hannibal, MO" },
  { label: "Warren, PA", value: "Warren, PA" },
  { label: "Alexandria, MN", value: "Alexandria, MN" },
  { label: "Urbana, OH", value: "Urbana, OH" },
  { label: "Greenwood, MS", value: "Greenwood, MS" },
  { label: "Cambridge, OH", value: "Cambridge, OH" },
  { label: "Williston, ND", value: "Williston, ND" },
  { label: "Defiance, OH", value: "Defiance, OH" },
  { label: "Sikeston, MO", value: "Sikeston, MO" },
  { label: "Safford, AZ", value: "Safford, AZ" },
  { label: "Jacksonville, IL", value: "Jacksonville, IL" },
  { label: "Ada, OK", value: "Ada, OK" },
  { label: "Brownwood, TX", value: "Brownwood, TX" },
  { label: "Crawfordsville, IN", value: "Crawfordsville, IN" },
  { label: "Logansport, IN", value: "Logansport, IN" },
  { label: "Scottsbluff, NE", value: "Scottsbluff, NE" },
  { label: "Natchitoches, LA", value: "Natchitoches, LA" },
  { label: "Newberry, SC", value: "Newberry, SC" },
  { label: "Lock Haven, PA", value: "Lock Haven, PA" },
  { label: "Centralia, IL", value: "Centralia, IL" },
  { label: "Easton, MD", value: "Easton, MD" },
  { label: "Owatonna, MN", value: "Owatonna, MN" },
  { label: "Mount Vernon, IL", value: "Mount Vernon, IL" },
  { label: "Laramie, WY", value: "Laramie, WY" },
  { label: "Murray, KY", value: "Murray, KY" },
  { label: "Fremont, NE", value: "Fremont, NE" },
  { label: "Bennington, VT", value: "Bennington, VT" },
  { label: "Sault Ste. Marie, MI", value: "Sault Ste. Marie, MI" },
  { label: "Campbellsville, KY", value: "Campbellsville, KY" },
  { label: "Dyersburg, TN", value: "Dyersburg, TN" },
  { label: "Escanaba, MI", value: "Escanaba, MI" },
  { label: "Mayfield, KY", value: "Mayfield, KY" },
  { label: "Kill Devil Hills, NC", value: "Kill Devil Hills, NC" },
  { label: "Sulphur Springs, TX", value: "Sulphur Springs, TX" },
  { label: "Hutchinson, MN", value: "Hutchinson, MN" },
  { label: "Coshocton, OH", value: "Coshocton, OH" },
  { label: "Huntington, IN", value: "Huntington, IN" },
  { label: "DeRidder, LA", value: "DeRidder, LA" },
  { label: "Vincennes, IN", value: "Vincennes, IN" },
  { label: "Bay City, TX", value: "Bay City, TX" },
  { label: "North Platte, NE", value: "North Platte, NE" },
  { label: "Peru, IN", value: "Peru, IN" },
  { label: "Pontiac, IL", value: "Pontiac, IL" },
  { label: "Lebanon, MO", value: "Lebanon, MO" },
  { label: "Newport, TN", value: "Newport, TN" },
  { label: "Decatur, IN", value: "Decatur, IN" },
  { label: "Vidalia, GA", value: "Vidalia, GA" },
  { label: "Brenham, TX", value: "Brenham, TX" },
  { label: "Vernal, UT", value: "Vernal, UT" },
  { label: "Ottumwa, IA", value: "Ottumwa, IA" },
  { label: "Butte, MT", value: "Butte, MT" },
  { label: "Corinth, MS", value: "Corinth, MS" },
  { label: "Brookhaven, MS", value: "Brookhaven, MS" },
  { label: "Emporia, KS", value: "Emporia, KS" },
  { label: "Jackson, WY", value: "Jackson, WY" },
  { label: "Big Spring, TX", value: "Big Spring, TX" },
  { label: "Effingham, IL", value: "Effingham, IL" },
  { label: "Dodge City, KS", value: "Dodge City, KS" },
  { label: "Watertown, SD", value: "Watertown, SD" },
  { label: "Angola, IN", value: "Angola, IN" },
  { label: "Dixon, IL", value: "Dixon, IL" },
  { label: "Laurinburg, NC", value: "Laurinburg, NC" },
  { label: "Taos, NM", value: "Taos, NM" },
  { label: "Brookings, SD", value: "Brookings, SD" },
  { label: "Americus, GA", value: "Americus, GA" },
  { label: "Columbus, NE", value: "Columbus, NE" },
  { label: "Taylorville, IL", value: "Taylorville, IL" },
  { label: "Arcadia, FL", value: "Arcadia, FL" },
  { label: "Lewisburg, TN", value: "Lewisburg, TN" },
  { label: "Seneca Falls, NY", value: "Seneca Falls, NY" },
  { label: "Dickinson, ND", value: "Dickinson, ND" },
  { label: "Washington, IN", value: "Washington, IN" },
  { label: "Troy, AL", value: "Troy, AL" },
  { label: "Malvern, AR", value: "Malvern, AR" },
  { label: "Frankfort, IN", value: "Frankfort, IN" },
  { label: "Madison, IN", value: "Madison, IN" },
  { label: "Brevard, NC", value: "Brevard, NC" },
  { label: "Susanville, CA", value: "Susanville, CA" },
  { label: "Martin, TN", value: "Martin, TN" },
  { label: "Plainview, TX", value: "Plainview, TX" },
  { label: "Dayton, TN", value: "Dayton, TN" },
  { label: "Jackson, OH", value: "Jackson, OH" },
  { label: "Cambridge, MD", value: "Cambridge, MD" },
  { label: "Paris, TN", value: "Paris, TN" },
  { label: "Juneau, AK", value: "Juneau, AK" },
  { label: "Coffeyville, KS", value: "Coffeyville, KS" },
  { label: "Las Vegas, NM", value: "Las Vegas, NM" },
  { label: "Berlin, NH", value: "Berlin, NH" },
  { label: "Cleveland, MS", value: "Cleveland, MS" },
  { label: "Hastings, NE", value: "Hastings, NE" },
  { label: "Beeville, TX", value: "Beeville, TX" },
  { label: "Kingsville, TX", value: "Kingsville, TX" },
  { label: "Wabash, IN", value: "Wabash, IN" },
  { label: "Breckenridge, CO", value: "Breckenridge, CO" },
  { label: "Albert Lea, MN", value: "Albert Lea, MN" },
  { label: "Sheridan, WY", value: "Sheridan, WY" },
  { label: "Union City, TN", value: "Union City, TN" },
  { label: "Miami, OK", value: "Miami, OK" },
  { label: "Iron Mountain, MI", value: "Iron Mountain, MI" },
  { label: "Jesup, GA", value: "Jesup, GA" },
  { label: "McPherson, KS", value: "McPherson, KS" },
  { label: "Kirksville, MO", value: "Kirksville, MO" },
  { label: "Ludington, MI", value: "Ludington, MI" },
  { label: "Bainbridge, GA", value: "Bainbridge, GA" },
  { label: "Alpena, MI", value: "Alpena, MI" },
  { label: "Washington Court House, OH", value: "Washington Court House, OH" },
  { label: "Hays, KS", value: "Hays, KS" },
  { label: "Fort Morgan, CO", value: "Fort Morgan, CO" },
  { label: "Van Wert, OH", value: "Van Wert, OH" },
  { label: "Kennett, MO", value: "Kennett, MO" },
  { label: "Weatherford, OK", value: "Weatherford, OK" },
  { label: "Mountain Home, ID", value: "Mountain Home, ID" },
  { label: "Mineral Wells, TX", value: "Mineral Wells, TX" },
  { label: "Lincoln, IL", value: "Lincoln, IL" },
  { label: "Silver City, NM", value: "Silver City, NM" },
  { label: "Elkins, WV", value: "Elkins, WV" },
  { label: "Macomb, IL", value: "Macomb, IL" },
  { label: "Camden, AR", value: "Camden, AR" },
  { label: "Crescent City, CA", value: "Crescent City, CA" },
  { label: "North Vernon, IN", value: "North Vernon, IN" },
  { label: "Thomaston, GA", value: "Thomaston, GA" },
  { label: "Grants, NM", value: "Grants, NM" },
  { label: "Bennettsville, SC", value: "Bennettsville, SC" },
  { label: "Fredericksburg, TX", value: "Fredericksburg, TX" },
  { label: "Toccoa, GA", value: "Toccoa, GA" },
  { label: "The Dalles, OR", value: "The Dalles, OR" },
  { label: "Greensburg, IN", value: "Greensburg, IN" },
  { label: "Indianola, MS", value: "Indianola, MS" },
  { label: "La Grande, OR", value: "La Grande, OR" },
  { label: "Ottawa, KS", value: "Ottawa, KS" },
  { label: "New Ulm, MN", value: "New Ulm, MN" },
  { label: "Lexington, NE", value: "Lexington, NE" },
  { label: "Great Bend, KS", value: "Great Bend, KS" },
  { label: "Spearfish, SD", value: "Spearfish, SD" },
  { label: "Wauchula, FL", value: "Wauchula, FL" },
  { label: "Marshall, MN", value: "Marshall, MN" },
  { label: "Deming, NM", value: "Deming, NM" },
  { label: "Mexico, MO", value: "Mexico, MO" },
  { label: "Fallon, NV", value: "Fallon, NV" },
  { label: "Altus, OK", value: "Altus, OK" },
  { label: "Uvalde, TX", value: "Uvalde, TX" },
  { label: "Hailey, ID", value: "Hailey, ID" },
  { label: "Steamboat Springs, CO", value: "Steamboat Springs, CO" },
  { label: "Summerville, GA", value: "Summerville, GA" },
  { label: "Moberly, MO", value: "Moberly, MO" },
  { label: "Middlesborough, KY", value: "Middlesborough, KY" },
  { label: "Woodward, OK", value: "Woodward, OK" },
  { label: "Prineville, OR", value: "Prineville, OR" },
  { label: "Hood River, OR", value: "Hood River, OR" },
  { label: "Forrest City, AR", value: "Forrest City, AR" },
  { label: "Connersville, IN", value: "Connersville, IN" },
  { label: "Mitchell, SD", value: "Mitchell, SD" },
  { label: "Marshall, MO", value: "Marshall, MO" },
  { label: "Brookings, OR", value: "Brookings, OR" },
  { label: "Yankton, SD", value: "Yankton, SD" },
  { label: "Wahpeton, ND", value: "Wahpeton, ND" },
  { label: "Magnolia, AR", value: "Magnolia, AR" },
  { label: "Elk City, OK", value: "Elk City, OK" },
  { label: "Liberal, KS", value: "Liberal, KS" },
  { label: "Worthington, MN", value: "Worthington, MN" },
  { label: "Oskaloosa, IA", value: "Oskaloosa, IA" },
  { label: "Pampa, TX", value: "Pampa, TX" },
  { label: "Clarksdale, MS", value: "Clarksdale, MS" },
  { label: "Sterling, CO", value: "Sterling, CO" },
  { label: "Beatrice, NE", value: "Beatrice, NE" },
  { label: "Jamestown, ND", value: "Jamestown, ND" },
  { label: "Levelland, TX", value: "Levelland, TX" },
  { label: "Grenada, MS", value: "Grenada, MS" },
  { label: "Maryville, MO", value: "Maryville, MO" },
  { label: "Arkadelphia, AR", value: "Arkadelphia, AR" },
  { label: "Dumas, TX", value: "Dumas, TX" },
  { label: "Guymon, OK", value: "Guymon, OK" },
  { label: "Borger, TX", value: "Borger, TX" },
  { label: "Pierre, SD", value: "Pierre, SD" },
  { label: "Huron, SD", value: "Huron, SD" },
  { label: "Storm Lake, IA", value: "Storm Lake, IA" },
  { label: "Cordele, GA", value: "Cordele, GA" },
  { label: "Evanston, WY", value: "Evanston, WY" },
  { label: "Raymondville, TX", value: "Raymondville, TX" },
  { label: "Port Lavaca, TX", value: "Port Lavaca, TX" },
  { label: "Othello, WA", value: "Othello, WA" },
  { label: "Vineyard Haven, MA", value: "Vineyard Haven, MA" },
  { label: "Parsons, KS", value: "Parsons, KS" },
  { label: "Price, UT", value: "Price, UT" },
  { label: "Portales, NM", value: "Portales, NM" },
  { label: "Los Alamos, NM", value: "Los Alamos, NM" },
  { label: "Hereford, TX", value: "Hereford, TX" },
  { label: "Andrews, TX", value: "Andrews, TX" },
  { label: "Spirit Lake, IA", value: "Spirit Lake, IA" },
  { label: "Fitzgerald, GA", value: "Fitzgerald, GA" },
  { label: "Winnemucca, NV", value: "Winnemucca, NV" },
  { label: "Maysville, KY", value: "Maysville, KY" },
  { label: "Snyder, TX", value: "Snyder, TX" },
  { label: "Helena, AR", value: "Helena, AR" },
  { label: "Spencer, IA", value: "Spencer, IA" },
  { label: "Atchison, KS", value: "Atchison, KS" },
  { label: "Fairfield, IA", value: "Fairfield, IA" },
  { label: "Vermillion, SD", value: "Vermillion, SD" },
  { label: "Sweetwater, TX", value: "Sweetwater, TX" },
  { label: "Pecos, TX", value: "Pecos, TX" },
  { label: "Zapata, TX", value: "Zapata, TX" },
  { label: "Ketchikan, AK", value: "Ketchikan, AK" },
  { label: "Craig, CO", value: "Craig, CO" },
  { label: "Vernon, TX", value: "Vernon, TX" },
  { label: "Lamesa, TX", value: "Lamesa, TX" },
];
